[package]
name = "mozwire"
description = "MozillaVPN wireguard configuration manager"
version = "0.1.0"
authors = ["Nils <nils@nilsand.re>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
base64 = "0.12.3"
clap = "2.33.3"
hostname = "0.3.1"
percent-encoding = "2.1.0"
rand = "0.7.3"
regex = "1.3.9"
reqwest = { version = "0.10.7", default-features = false, features = ["rustls-tls", "blocking", "json"] }
serde = { version = "1.0.115", features = ["derive"] }
sys-info = "0.7.0"
webbrowser = "0.5.5"
x25519-dalek = "0.6.0"
